### ISSUE TITLE
Placeholder values under values-v30 folder are not dynamically applied

### ISSUE THREAD

**Issue by renjithk** [LikeTheSalad/android-stem#115]
I have a string translation here 

 ```
    <string name="app_name">MyApp</string>
   <string name="app_permission_warning">
        Please enable the 'Storage’ permission for ${app_name}.
    </string>
```
This is working all well. Now I want a slightly different string for API 30 and above. So I added the variation under `res/values-v30/strings.xml`
```
    <string name="app_permission_warning">
        Please enable the ‘Files and media’ permission for ${app_name}.
    </string>
```
However, on the resolved.xml, I don't see the ones from `res/values-v30`. I did a clean and build the project with no result.

**Comment by LikeTheSalad** [comment]
Hi @renjithk 

Thank you for your feedback. I need to add support for api-specific values folders. Will do so as soon as I can.

**Comment by LikeTheSalad** [comment]
The new version `2.11.0` should fix this. Feel free to reopen if you still see the issue with that version.
