### ISSUE TITLE
Namespace for prefix 'ns1' has not been declared.

### ISSUE THREAD

**Issue by YuuHaruna** [LikeTheSalad/android-stem#26]
Hi @LikeTheSalad, I'm using your stem plugin in my project. But when I use `com.likethesalad.android:stem-plugin:2.1.1`, I receive this error when build project: `Namespace for prefix 'ns1' has not been declared.`, which I haven't seen in version 2.0.0. What should I do now?

**Comment by LikeTheSalad** [comment]
Hi @YuuHaruna, please can you share the error stacktrace? I need to know where in the plugin's code this issue is being triggered, so the stacktrace will help there.

Also, just to make sure, are you defining any property within your string resources (templates or placeholders) that uses an XML namespace named `ns1`?

**Comment by LikeTheSalad** [comment]
Hi @YuuHaruna, thanks, this is a very interesting issue, I think I know what's going on. So amongst the targets of Stem, we have the build.gradle generated Android strings and also strings coming from 'stem-library's, and what those have in common is that they've been processed by the Android Gradle plugin, which apparently ([according to this thread](https://stackoverflow.com/questions/19526945/android-gradle-merged-values-xml-uses-wrong-namespace)) tends to generate or rename XML namespaces for them...

Now, even though the above stackoverflow link mentions some solutions that involve removing custom namespaces, I think those are sometimes needed, so I rather make Stem aware of them to avoid these kinds of crashes in the future, which I believe is possible. So I'm going to start working on a patch for it.

**Comment by LikeTheSalad** [comment]
I've just released version `2.2.0` which takes care of handling namespaces correctly. Please feel free to reopen this ticket if you still find the same issue after upgrading Stem.
