### ISSUE TITLE
Upgrading from 2.1.1 to 2.2.0: the project does not compile anymore.

### ISSUE THREAD

**Issue by bmarty** [LikeTheSalad/android-stem#29]
Here is the compilation error:

> java.lang.NoClassDefFoundError: com/likethesalad/android/templates/common/plugins/BaseTemplatesProcessorPlugin

See https://github.com/vector-im/element-android/pull/6882

Not sure if this is due to another dependency upgrade, since with this other PR, from an older version of develop, it was compiling fine: https://github.com/vector-im/element-android/pull/6838

I am investigating in parallel.

**Comment by LikeTheSalad** [comment]
Hi @bmarty thanks for your feedback! It's not another dependency no worries, it's Stem. It seems like one of Stem's dependencies (the one containing that missing class) isn't being fetched by Gradle for some reason. I already created [an issue for it](https://github.com/gradle/gradle/issues/21638), however in the meantime I'm going to release a patch that doesn't rely on Gradle fetching other dependencies to avoid it altogether.

Cheers!

**Comment by LikeTheSalad** [comment]
Please try again but with the just released version `2.2.1` it should be working fine.

**Comment by bmarty** [comment]
Yes, it seems to be fine now. Thanks!
Ref: https://github.com/vector-im/element-android/pull/6983

**Comment by LikeTheSalad** [comment]
Awesome! I'm closing this issue then, cheers.
