### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by green-green-avk** [LikeTheSalad/android-stem#37]
```xml
<string name="fullVersionName">${versionName} <i>downgradable</i></string>
```
is expanded as
```xml
<string name="fullVersionName">MkIV-dev40 downgradable</string>
```
I prefer to have an ability to use [`Resources.getText()`](https://developer.android.com/reference/android/content/res/Resources#getText(int)).

**Comment by LikeTheSalad** [comment]
Hi @green-green-avk - I see what you mean, although I've taken a look at how to accomplish this, and it seems a bit complicated to tell the XML reader to ignore some xml-like tags. So I was wondering if you've tried to escape those chars? like so:

```xml
<string name="fullVersionName">${versionName} &lt;i&gt;downgradable&lt;/i&gt;</string>
```

Would it work for your use case?

**Comment by green-green-avk** [comment]
Umm... I asked about it purely for the sake of [`Resources.getText()`](https://developer.android.com/reference/android/content/res/Resources#getText(int))...

Your proposed workaround does nothing to solve it. There MUST be real tags here.

**Comment by LikeTheSalad** [comment]
I can't see the problem though, if you need the tags to be available at runtime, escaping those chars will make them available when calling Resources.getText - Feel free to provide some specific example or a PR if you know what to change to make your use case work.

**Comment by green-green-avk** [comment]
No. They will be represented as chars and not a tag.
The specific example is already here, see the first message.

Steps to reproduce:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
 <string name="versionName">1.1.1</string>
 <string name="fullVersionName">${versionName} <i>downgradable</i></string>
 <string name="fullVersionName2">1.1.1 <i>downgradable</i></string>
</resources>
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
 android:layout_width="match_parent"
 android:layout_height="match_parent">
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:text="@string/fullVersionName" />
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:text="@string/fullVersionName2" />
</LinearLayout>
```
Just compare the lines.

**Comment by LikeTheSalad** [comment]
I see. So it all comes down to how parsing XMLs work. Unlike raw strings created by you, templates have to be read by Stem first, and during this process all tags are processed, meaning that by the time the templates are resolved, no tags other than `<string>` ones would be left.

There's a couple of questions on this, like [this one for example](https://stackoverflow.com/questions/12319595/xml-parsing-in-java-ignore-tags-as-value), that doesn't solve the issue on the XML parser side but rather on the input XML instead, using CDATA. And there are others like [this one](https://stackoverflow.com/a/7130661/7031224) which explain how to accomplish what you want at runtime using Html.fromHtml or [SpannableString](https://developer.android.com/reference/android/text/SpannableString). I suggest taking a look at those alternatives, if you  want to have everything XML-driven, then probably using something like `<string name="fullVersionName">${versionName} <![CDATA[<i>downgradable</i>]]></string>` might work.

It's the nature of it all, of course we could get creative and probably preprocess every input XML file looking for tags inside string values and automatically escaping them or something the like, but it's just too much trouble for a feature that's not the core functionality of this tool, which is to resolve placeholders. If you want to take the time though, feel free to modify [this class](https://github.com/LikeTheSalad/resource-locator/blob/f3361bdefc1850b93bf8398bf1d1b9642a814da2/string-android-resource-locator/src/main/java/com/likethesalad/android/string/resources/locator/extractor/StringXmlResourceExtractor.kt#L63), which is where the XML strings are read, and create a PR. Just bear in mind that performance is important when processing a lot of strings, so the in the case you want to provide a solution, it shouldn't cause much performance penalties when reading XML inputs.

**Comment by green-green-avk** [comment]
Yep. I prefer not to use any runtime crutches like `Html.fromHtml`. It's purely a compile time task and runtime must not be affected.

**Comment by green-green-avk** [comment]
The best way to improve it is to have an entire XML subtree substitution...

Imagine, you could:
`xml/extra_preferences.xml` (flavor-dependent):
```xml
<?xml version="1.0" encoding="utf-8"?>
<preference-headers>
    <header
        android:fragment="extra_blah"
        android:icon="@drawable/extra_blah"
        android:title="@string/extra_blah" />
    <!-- ... -->
</preference-headers>
```
`xml/preferences.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<preference-headers>
    <!-- All nodes inside the root node -->
    ${xml/extra_preferences/*/*}
    <header
        android:fragment="blah"
        android:icon="@drawable/blah"
        android:title="@string/blah" />
    <!-- ... -->
</preference-headers>
```
