### ISSUE TITLE
Cannot replace template string in Arabic

### ISSUE THREAD

**Issue by xiaolingcong** [LikeTheSalad/android-stem#38]
Cannot replace template string in Arabic

**Comment by LikeTheSalad** [comment]
I'm going to need the following info:
- In which folder is your arabic template? `values` or `values-ar`?
- If your template is in `values-ar`, do you define your template only in that folder? Or there's another template with the same name in the `values` folder?

**Comment by xiaolingcong** [comment]
In values-ar ，Android stuido change  ${device_name}   to    {device_name}$.   Modify it ${device_name}  is ok
