### ISSUE TITLE
Plugin is not considering style elements like <b></b> inside strings

### ISSUE THREAD

**Issue by febinmathew** [LikeTheSalad/android-stem#85]
When specifying the string as below:

`<string name="need_location_permission">${app_name} requires access to your <b>location</b> to fetch data. Please grant this permission to continue.</string>`

It is converted to:

`<string name="need_location_permission">Telephram requires access to your location to find people nearby. Please grant this permission to continue.</string>`

The styling data is lost.

**Comment by LikeTheSalad** [comment]
Hi @febinmathew 

Support for html style tags has been added in the latest release (`2.10.0`). Please feel free to reopen this issue if the problem persists with the new version.
